version: '3.7'

services:
  animus:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 9229:9229
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - postgres
      - redis
  redis:
    container_name: 'redis'
    image: redis:6.2.6-alpine
    networks:
      - network
    ports:
      - 6379:${STORE_PORT}
  postgres:
    container_name: 'postgres'
    image: postgres:14.2-alpine
    networks:
      - network
    env_file:
      - .env
    logging:
      driver: none
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:${POSTGRES_PORT}
networks:
  network:
